/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== index.html ==================
static const unsigned char temp_binary_data_0[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>AETHER // Polyphonic MIDI Delay</title>\n"
"    <link rel=\"stylesheet\" href=\"styles.css\">\n"
"    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
"    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
"    <link href=\"https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;700&display=swap\" rel=\"stylesheet\">\n"
"</head>\n"
"<style>\n"
"    #build-version-label {\n"
"        position: absolute;\n"
"        bottom: 6px;\n"
"        right: 10px;\n"
"        font-family: 'IBM Plex Mono', monospace;\n"
"        font-size: 9px;\n"
"        color: rgba(255,255,255,0.22);\n"
"        letter-spacing: 0.04em;\n"
"        pointer-events: none;\n"
"        z-index: 9999;\n"
"        user-select: none;\n"
"    }\n"
"</style>\n"
"<body>\n"
"    <div class=\"crt-overlay\"></div>\n"
"    <div id=\"app-container\">\n"
"        <!-- Main Panel Header -->\n"
"        <header class=\"main-header border-bottom\">\n"
"            <div class=\"header-left\">\n"
"                <!-- Power switch -->\n"
"                <div class=\"control-group text-center\">\n"
"                    <span class=\"label-tiny\">POWER</span>\n"
"                    <button id=\"power-btn\" class=\"toggle-btn circular-btn\">\n"
"                        <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"                            <path d=\"M18.36 6.64a9 9 0 1 1-12.73 0\" />\n"
"                            <line x1=\"12\" y1=\"2\" x2=\"12\" y2=\"12\" />\n"
"                        </svg>\n"
"                    </button>\n"
"                </div>\n"
"                <!-- Branding -->\n"
"                <div class=\"branding\">\n"
"                    <h1 class=\"logo crt-glow\">AETHER</h1>\n"
"                    <div class=\"taglines\">\n"
"                        <span class=\"tagline\">POLYPHONIC MIDI DELAY</span>\n"
"                        <span class=\"tagline subtagline\">BY DARKINTEGER</span>\n"
"                    </div>\n"
"                </div>\n"
"                <!-- Delay Time / Division Matrix -->\n"
"                <div class=\"delay-matrix-container border-left\">\n"
"                    <span class=\"label-tiny section-label\">DELAY TIME MATRIX</span>\n"
"                    <div class=\"matrix-grid\">\n"
"                        <!-- Row 1: Straight -->\n"
"                        <button class=\"matrix-btn\" data-div=\"1/1\">1/1</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/2\">1/2</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/4\">1/4</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/8\">1/8</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/16\">1/16</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/32\">1/32</button>\n"
"\n"
"                        <!-- Row 2: Dotted -->\n"
"                        <button class=\"matrix-btn\" data-div=\"1/1d\">1/1D</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/2d\">1/2D</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/4d\">1/4D</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/8d\">1/8D</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/16d\">1/16D</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/32d\">1/32D</button>\n"
"\n"
"                        <!-- Row 3: Triplet -->\n"
"                        <button class=\"matrix-btn\" data-div=\"1/1t\">1/1T</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/2t\">1/2T</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/4t\">1/4T</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/8t\">1/8T</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/16t\">1/16T</button>\n"
"                        <button class=\"matrix-btn\" data-div=\"1/32t\">1/32T</button>\n"
"                    </div>\n"
"                    <!-- Delay Time Footer Row (Manual, Value, Kill) -->\n"
"                    <div class=\"delay-footer\">\n"
"                        <button id=\"kill-btn\" class=\"delay-footer-btn flex-2\">KILL ON STOP</button>\n"
"                        <button id=\"manual-btn\" class=\"delay-footer-btn flex-3\">MANUAL (MS)</button>\n"
"                        <div id=\"ms-value-box\" class=\"ms-drag-box flex-1\">\n"
"                            <span id=\"ms-value-text\">500</span>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"        </header>\n"
"\n"
"        <!-- Main Lanes Workspace -->\n"
"        <main class=\"lanes-workspace\">\n"
"            <!-- Lane templates generated dynamically in app.js -->\n"
"            <div id=\"lanes-container\"></div>\n"
"\n"
"            <!-- Step Count Lane -->\n"
"            <div class=\"step-count-container\">\n"
"                <div class=\"step-count-header\">\n"
"                    <span id=\"step-count-label\" class=\"lane-title\">STEP COUNT: 15</span>\n"
"                </div>\n"
"                <div id=\"step-count-track\" class=\"step-count-track\">\n"
"                    <!-- 15 segments generated dynamically in app.js -->\n"
"                </div>\n"
"            </div>\n"
"\n"
"            <!-- Snapshots Container -->\n"
"            <div class=\"snapshot-container\">\n"
"                <div class=\"snapshot-header\">\n"
"                    <span class=\"lane-title\">SNAPSHOT PRESETS</span>\n"
"                    <div class=\"snapshot-actions\">\n"
"                        <button id=\"copy-snap-btn\" class=\"action-btn\" title=\"Copy Active Snapshot\">C</button>\n"
"                        <button id=\"paste-snap-btn\" class=\"action-btn\" title=\"Paste to Selected Snapshot\">P</button>\n"
"                        <button id=\"kill-on-switch-btn\" class=\"action-btn wide-action-btn\" title=\"Kill ringing delays on snapshot change\">KILL ON SWITCH</button>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"snapshot-radio-group\">\n"
"                    <button class=\"snapshot-btn active\" data-index=\"0\">1</button>\n"
"                    <button class=\"snapshot-btn\" data-index=\"1\">2</button>\n"
"                    <button class=\"snapshot-btn\" data-index=\"2\">3</button>\n"
"                    <button class=\"snapshot-btn\" data-index=\"3\">4</button>\n"
"                    <button class=\"snapshot-btn\" data-index=\"4\">5</button>\n"
"                    <button class=\"snapshot-btn\" data-index=\"5\">6</button>\n"
"                    <button class=\"snapshot-btn\" data-index=\"6\">7</button>\n"
"                    <button class=\"snapshot-btn\" data-index=\"7\">8</button>\n"
"                    <button class=\"snapshot-btn\" data-index=\"8\">9</button>\n"
"                </div>\n"
"                <div class=\"snapshot-edit-group\">\n"
"                    <button class=\"snapshot-edit-btn active\" data-index=\"0\"></button>\n"
"                    <button class=\"snapshot-edit-btn\" data-index=\"1\"></button>\n"
"                    <button class=\"snapshot-edit-btn\" data-index=\"2\"></button>\n"
"                    <button class=\"snapshot-edit-btn\" data-index=\"3\"></button>\n"
"                    <button class=\"snapshot-edit-btn\" data-index=\"4\"></button>\n"
"                    <button class=\"snapshot-edit-btn\" data-index=\"5\"></button>\n"
"                    <button class=\"snapshot-edit-btn\" data-index=\"6\"></button>\n"
"                    <button class=\"snapshot-edit-btn\" data-index=\"7\"></button>\n"
"                    <button class=\"snapshot-edit-btn\" data-index=\"8\"></button>\n"
"                </div>\n"
"            </div>\n"
"        </main>\n"
"        <div id=\"build-version-label\"></div>\n"
"    </div>\n"
"    <script src=\"app.js\"></script>\n"
"</body>\n"
"</html>\n";

const char* index_html = (const char*) temp_binary_data_0;

//================== app.js ==================
static const unsigned char temp_binary_data_1[] =
"// AETHER UI Logic & C++ Host Communication Bridge\n"
"const BUILD_VERSION = 'build 1.0.14';\n"
"\n"
"// 18 Sync divisions strings\n"
"const SYNC_DIVISIONS = [\n"
"    '1/1', '1/2', '1/4', '1/8', '1/16', '1/32',\n"
"    '1/1d', '1/2d', '1/4d', '1/8d', '1/16d', '1/32d',\n"
"    '1/1t', '1/2t', '1/4t', '1/8t', '1/16t', '1/32t'\n"
"];\n"
"\n"
"// UI Local State\n"
"let state = {\n"
"    isEnabled: true,\n"
"    delayMode: 'sync',\n"
"    delayTimeMs: 500,\n"
"    syncDivision: '1/4',\n"
"    stepCount: 15,\n"
"    killOnStop: true,\n"
"    killOnSwitch: false,\n"
"    activeSnapshot: 0,\n"
"    editSnapshot: 0,\n"
"    steps: Array.from({ length: 15 }, (_, i) => ({\n"
"        pitch: 0,\n"
"        velocity: Math.round(127 - (i * (126 / 14))),\n"
"        modwheel: 0,\n"
"        probability: 100,\n"
"        muted: false\n"
"    }))\n"
"};\n"
"\n"
"// Drag tracking variables\n"
"let activeDraggingLane = null; // { property, element, min, max, isBipolar }\n"
"let isDraggingStepCount = false;\n"
"let isDraggingMs = false;\n"
"let msStartY = 0;\n"
"let msStartValue = 500;\n"
"\n"
"// Bridge: Send call to C++\n"
"let juceBridgeReady = false;\n"
"const juceMessageQueue = [];\n"
"\n"
"function sendParamToCpp(param, val) {\n"
"    if (juceBridgeReady) {\n"
"        const resultId = Math.floor(Math.random() * 1000000);\n"
"        window.__JUCE__.backend.emitEvent(\"__juce__invoke\", {\n"
"            name: \"sendParamToCpp\",\n"
"            params: [param, val],\n"
"            resultId: resultId\n"
"        });\n"
"    } else if (window.__JUCE__ && window.__JUCE__.backend) {\n"
"        juceBridgeReady = true;\n"
"        const resultId = Math.floor(Math.random() * 1000000);\n"
"        window.__JUCE__.backend.emitEvent(\"__juce__invoke\", {\n"
"            name: \"sendParamToCpp\",\n"
"            params: [param, val],\n"
"            resultId: resultId\n"
"        });\n"
"    } else {\n"
"        juceMessageQueue.push({ param, val });\n"
"        console.log(\"C++ Bridge Call Queued: \" + param + \" = \" + val);\n"
"    }\n"
"}\n"
"\n"
"function checkJuceBridge() {\n"
"    if (window.__JUCE__ && window.__JUCE__.backend) {\n"
"        juceBridgeReady = true;\n"
"        console.log(\"JUCE Bridge is ready. Flushing queue of length: \" + juceMessageQueue.length);\n"
"        while (juceMessageQueue.length > 0) {\n"
"            const msg = juceMessageQueue.shift();\n"
"            sendParamToCpp(msg.param, msg.val);\n"
"        }\n"
"    } else {\n"
"        setTimeout(checkJuceBridge, 30);\n"
"    }\n"
"}\n"
"checkJuceBridge();\n"
"\n"
"// --------------------------------------------------------------------------\n"
"// UI Layout Builders\n"
"// --------------------------------------------------------------------------\n"
"\n"
"const diceIconSvg = `<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"    <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\" />\n"
"    <circle cx=\"8.5\" cy=\"8.5\" r=\"1.5\" fill=\"currentColor\" />\n"
"    <circle cx=\"15.5\" cy=\"15.5\" r=\"1.5\" fill=\"currentColor\" />\n"
"    <circle cx=\"12\" cy=\"12\" r=\"1.5\" fill=\"currentColor\" />\n"
"</svg>`;\n"
"\n"
"const resetIconSvg = `<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"    <path d=\"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8\" />\n"
"    <path d=\"M3 3v5h5\" />\n"
"</svg>`;\n"
"\n"
"// Generate dynamically rendered sequencer lanes\n"
"function buildLanes() {\n"
"    const container = document.getElementById(\"lanes-container\");\n"
"    container.innerHTML = \"\";\n"
"\n"
"    const lanesConfig = [\n"
"        { label: \"Pitch Shift\", prop: \"pitch\", min: -24, max: 24, isBipolar: true },\n"
"        { label: \"Velocity\", prop: \"velocity\", min: 1, max: 127 },\n"
"        { label: \"Modwheel\", prop: \"modwheel\", min: 0, max: 127 },\n"
"        { label: \"Probability\", prop: \"probability\", min: 0, max: 100 },\n"
"        { label: \"Mute\", prop: \"muted\", min: 0, max: 1 }\n"
"    ];\n"
"\n"
"    lanesConfig.forEach(config => {\n"
"        const laneWrapper = document.createElement(\"div\");\n"
"        laneWrapper.className = \"lane-wrapper\";\n"
"        laneWrapper.setAttribute(\"data-prop\", config.prop);\n"
"\n"
"        // Header\n"
"        const header = document.createElement(\"div\");\n"
"        header.className = \"lane-header\";\n"
"        header.innerHTML = `\n"
"            <div class=\"lane-title-group\">\n"
"                <div class=\"lane-actions\">\n"
"                    <button class=\"action-btn r-btn\" title=\"Randomize Lane\">${diceIconSvg}</button>\n"
"                    <button class=\"action-btn rst-btn\" title=\"Reset Lane\">${resetIconSvg}</button>\n"
"                </div>\n"
"                <span class=\"lane-title\">${config.label}</span>\n"
"            </div>\n"
"        `;\n"
"\n"
"        // Register action buttons click\n"
"        header.querySelector(\".r-btn\").onclick = () => {\n"
"            randomizeLaneLocal(config.prop, config.min, config.max);\n"
"            sendParamToCpp(\"randomizeLane\", config.prop);\n"
"        };\n"
"        header.querySelector(\".rst-btn\").onclick = () => {\n"
"            resetLaneLocal(config.prop);\n"
"            sendParamToCpp(\"resetLane\", config.prop);\n"
"        };\n"
"\n"
"        // Grid container\n"
"        const grid = document.createElement(\"div\");\n"
"        grid.className = \"steps-grid\";\n"
"        grid.style.height = config.prop === 'muted' ? \"24px\" : \"128px\";\n"
"\n"
"        if (config.isBipolar) {\n"
"            const line = document.createElement(\"div\");\n"
"            line.className = \"bipolar-center-line\";\n"
"            line.style.top = \"calc(50% - 14px)\"; // half of the 28px value label\n"
"            grid.appendChild(line);\n"
"        }\n"
"\n"
"        // Draw 15 steps\n"
"        for (let i = 0; i < 15; i++) {\n"
"            const col = document.createElement(\"div\");\n"
"            col.className = `step-column${i >= state.stepCount ? ' inactive' : ''}`;\n"
"            col.setAttribute(\"data-step\", i);\n"
"\n"
"            const barContainer = document.createElement(\"div\");\n"
"            barContainer.className = \"step-bar-container\";\n"
"\n"
"            if (config.prop === 'muted') {\n"
"                const muteBox = document.createElement(\"div\");\n"
"                muteBox.className = \"step-mute-box muted\";\n"
"                barContainer.appendChild(muteBox);\n"
"            } else if (config.isBipolar) {\n"
"                const fill = document.createElement(\"div\");\n"
"                fill.className = \"step-bar-bipolar\";\n"
"                barContainer.appendChild(fill);\n"
"            } else {\n"
"                const fill = document.createElement(\"div\");\n"
"                fill.className = \"step-bar-fill\";\n"
"                barContainer.appendChild(fill);\n"
"            }\n"
"\n"
"            col.appendChild(barContainer);\n"
"\n"
"            if (config.prop !== 'muted') {\n"
"                const label = document.createElement(\"div\");\n"
"                label.className = \"step-value-label\";\n"
"                col.appendChild(label);\n"
"            }\n"
"\n"
"            // Drag registration on down\n"
"            col.onmousedown = (e) => {\n"
"                if (!state.isEnabled) return;\n"
"                if (config.prop === 'muted') {\n"
"                    // Mute lane is click-only\n"
"                    state.steps[i].muted = !state.steps[i].muted;\n"
"                    updateStepUI(config.prop, i);\n"
"                    sendParamToCpp(\"stepUpdate\", JSON.stringify({ index: i, property: \"muted\", value: state.steps[i].muted }));\n"
"                } else {\n"
"                    activeDraggingLane = {\n"
"                        property: config.prop,\n"
"                        element: grid,\n"
"                        min: config.min,\n"
"                        max: config.max,\n"
"                        isBipolar: config.isBipolar\n"
"                    };\n"
"                    updateStepFromMouse(e, grid, config.prop, config.min, config.max, config.isBipolar);\n"
"                }\n"
"            };\n"
"\n"
"            grid.appendChild(col);\n"
"        }\n"
"\n"
"        laneWrapper.appendChild(header);\n"
"        laneWrapper.appendChild(grid);\n"
"        container.appendChild(laneWrapper);\n"
"    });\n"
"\n"
"    // Generate 15 Step Count segments\n"
"    const track = document.getElementById(\"step-count-track\");\n"
"    track.innerHTML = \"\";\n"
"    for (let i = 0; i < 15; i++) {\n"
"        const seg = document.createElement(\"div\");\n"
"        seg.className = `step-count-segment${i < state.stepCount ? ' active' : ''}`;\n"
"        track.appendChild(seg);\n"
"    }\n"
"}\n"
"\n"
"// --------------------------------------------------------------------------\n"
"// UI State Updates\n"
"// --------------------------------------------------------------------------\n"
"\n"
"// Update a single step visual bar\n"
"function updateStepUI(property, index) {\n"
"    const lane = document.querySelector(`.lane-wrapper[data-prop=\"${property}\"]`);\n"
"    if (!lane) return;\n"
"\n"
"    const col = lane.querySelectorAll(\".step-column\")[index];\n"
"    if (!col) return;\n"
"\n"
"    const val = state.steps[index][property];\n"
"\n"
"    if (property === 'muted') {\n"
"        const muteBox = col.querySelector(\".step-mute-box\");\n"
"        if (muteBox) {\n"
"            if (val) {\n"
"                muteBox.className = \"step-mute-box muted\";\n"
"            } else {\n"
"                muteBox.className = \"step-mute-box unmuted\";\n"
"            }\n"
"        }\n"
"    } else {\n"
"        const fill = col.querySelector(\".step-bar-fill, .step-bar-bipolar\");\n"
"        const label = col.querySelector(\".step-value-label\");\n"
"\n"
"        // Format label text\n"
"        if (label) {\n"
"            let labelStr = val.toString();\n"
"            if (property === 'probability') labelStr = `${val}%`;\n"
"            else if (property === 'pitch' && val > 0) labelStr = `+${val}`;\n"
"            label.textContent = labelStr;\n"
"        }\n"
"\n"
"        // Draw fill bar\n"
"        if (fill) {\n"
"            const min = property === 'pitch' ? -24 : (property === 'velocity' ? 1 : 0);\n"
"            const max = property === 'pitch' ? 24 : (property === 'velocity' ? 127 : 100);\n"
"\n"
"            if (property === 'pitch') {\n"
"                const absVal = Math.abs(val);\n"
"                const heightPercent = (absVal / 24) * 50;\n"
"                fill.style.height = `${heightPercent}%`;\n"
"                if (val >= 0) {\n"
"                    fill.style.top = \"auto\";\n"
"                    fill.style.bottom = \"50%\";\n"
"                } else {\n"
"                    fill.style.top = \"50%\";\n"
"                    fill.style.bottom = \"auto\";\n"
"                }\n"
"            } else {\n"
"                const percent = ((val - min) / (max - min)) * 100;\n"
"                fill.style.height = `${percent}%`;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"// Update all UI elements according to the main `state`\n"
"function updateUIFromState() {\n"
"    // 1. Power Switch\n"
"    const powerBtn = document.getElementById(\"power-btn\");\n"
"    const appContainer = document.getElementById(\"app-container\");\n"
"    if (state.isEnabled) {\n"
"        powerBtn.classList.add(\"active\");\n"
"        appContainer.classList.remove(\"disabled\");\n"
"    } else {\n"
"        powerBtn.classList.remove(\"active\");\n"
"        appContainer.classList.add(\"disabled\");\n"
"    }\n"
"\n"
"\n"
"\n"
"    // 3. Step Count Slider\n"
"    document.getElementById(\"step-count-label\").textContent = `STEP COUNT: ${state.stepCount}`;\n"
"    document.querySelectorAll(\".step-count-segment\").forEach((seg, i) => {\n"
"        seg.classList.toggle(\"active\", i < state.stepCount);\n"
"    });\n"
"    // Update active/inactive state of lane columns\n"
"    document.querySelectorAll(\".step-column\").forEach(col => {\n"
"        const stepIdx = parseInt(col.getAttribute(\"data-step\"));\n"
"        col.classList.toggle(\"inactive\", stepIdx >= state.stepCount);\n"
"    });\n"
"\n"
"    // 4. Delay Time Matrix & Footer\n"
"    const isMs = state.syncDivision === 'ms';\n"
"    document.getElementById(\"manual-btn\").classList.toggle(\"active\", isMs);\n"
"    document.getElementById(\"ms-value-box\").classList.toggle(\"active\", isMs);\n"
"    document.getElementById(\"ms-value-text\").textContent = Math.round(state.delayTimeMs);\n"
"    document.getElementById(\"kill-btn\").classList.toggle(\"active\", state.killOnStop);\n"
"    \n"
"    // 5b. Update kill-on-switch button\n"
"    const kosBtn = document.getElementById(\"kill-on-switch-btn\");\n"
"    if (kosBtn) kosBtn.classList.toggle(\"active\", state.killOnSwitch);\n"
"\n"
"    document.querySelectorAll(\".matrix-btn\").forEach(btn => {\n"
"        btn.classList.toggle(\"active\", !isMs && btn.getAttribute(\"data-div\") === state.syncDivision);\n"
"    });\n"
"\n"
"    // 5. Steps & Lanes\n"
"    for (let i = 0; i < 15; i++) {\n"
"        updateStepUI(\"pitch\", i);\n"
"        updateStepUI(\"velocity\", i);\n"
"        updateStepUI(\"modwheel\", i);\n"
"        updateStepUI(\"probability\", i);\n"
"        updateStepUI(\"muted\", i);\n"
"    }\n"
"\n"
"    // 6. Snapshot Presets Buttons\n"
"    document.querySelectorAll(\".snapshot-btn\").forEach((btn, i) => {\n"
"        btn.classList.toggle(\"active\", i === state.activeSnapshot);\n"
"    });\n"
"    document.querySelectorAll(\".snapshot-edit-btn\").forEach((btn, i) => {\n"
"        btn.classList.toggle(\"active\", i === state.editSnapshot);\n"
"    });\n"
"}\n"
"\n"
"// Calculate and apply step value changes from drag/mouse movement\n"
"function updateStepFromMouse(e, gridElement, property, min, max, isBipolar) {\n"
"    const rect = gridElement.getBoundingClientRect();\n"
"    const relativeX = e.clientX - rect.left;\n"
"    const stepWidth = rect.width / 15;\n"
"    const stepIndex = Math.max(0, Math.min(14, Math.floor(relativeX / stepWidth)));\n"
"\n"
"    if (stepIndex >= state.stepCount) return;\n"
"\n"
"    // Calculate vertical value\n"
"    const barAreaHeight = rect.height - (isBipolar ? 0 : 28); // subtract label height for unipolar\n"
"    const relativeY = Math.max(0, Math.min(barAreaHeight, e.clientY - rect.top));\n"
"    const normalized = 1 - (relativeY / barAreaHeight);\n"
"    const value = Math.round(min + (normalized * (max - min)));\n"
"\n"
"    if (state.steps[stepIndex][property] !== value) {\n"
"        state.steps[stepIndex][property] = value;\n"
"        updateStepUI(property, stepIndex);\n"
"        sendParamToCpp(\"stepUpdate\", JSON.stringify({ index: stepIndex, property: property, value: value }));\n"
"    }\n"
"}\n"
"\n"
"// --------------------------------------------------------------------------\n"
"// Local Modifications Helpers\n"
"// --------------------------------------------------------------------------\n"
"\n"
"function randomizeLaneLocal(property, min, max) {\n"
"    for (let i = 0; i < 15; i++) {\n"
"        if (property === 'muted') {\n"
"            state.steps[i].muted = Math.random() > 0.5;\n"
"        } else {\n"
"            state.steps[i][property] = Math.round(min + Math.random() * (max - min));\n"
"        }\n"
"        updateStepUI(property, i);\n"
"    }\n"
"}\n"
"\n"
"function resetLaneLocal(property) {\n"
"    for (let i = 0; i < 15; i++) {\n"
"        let val;\n"
"        switch(property) {\n"
"            case 'pitch': val = 0; break;\n"
"            case 'velocity': val = Math.round(127 - (i * (126 / 14))); break;\n"
"            case 'modwheel': val = 0; break;\n"
"            case 'probability': val = 100; break;\n"
"            case 'muted': val = false; break;\n"
"        }\n"
"        state.steps[i][property] = val;\n"
"        updateStepUI(property, i);\n"
"    }\n"
"}\n"
"\n"
"// Update Step Count from pointer position\n"
"function updateStepCountFromMouse(clientX) {\n"
"    const track = document.getElementById(\"step-count-track\");\n"
"    const rect = track.getBoundingClientRect();\n"
"    const width = rect.width;\n"
"    const relativeX = Math.max(0, Math.min(width, clientX - rect.left));\n"
"    const normalized = relativeX / width;\n"
"    const newCount = Math.max(1, Math.min(15, Math.ceil(normalized * 15)));\n"
"\n"
"    if (state.stepCount !== newCount) {\n"
"        state.stepCount = newCount;\n"
"        document.getElementById(\"step-count-label\").textContent = `STEP COUNT: ${state.stepCount}`;\n"
"        document.querySelectorAll(\".step-count-segment\").forEach((seg, i) => {\n"
"            seg.classList.toggle(\"active\", i < newCount);\n"
"        });\n"
"        document.querySelectorAll(\".step-column\").forEach(col => {\n"
"            const stepIdx = parseInt(col.getAttribute(\"data-step\"));\n"
"            col.classList.toggle(\"inactive\", stepIdx >= newCount);\n"
"        });\n"
"        sendParamToCpp(\"stepCount\", newCount);\n"
"    }\n"
"}\n"
"\n"
"// Drag delay MS value box\n"
"function updateMsFromMouse(clientY) {\n"
"    const deltaY = msStartY - clientY;\n"
"    const sensitivity = 0.5;\n"
"    const newVal = Math.max(1, Math.min(2000, Math.round(msStartValue + (deltaY * sensitivity))));\n"
"    if (state.delayTimeMs !== newVal) {\n"
"        state.delayTimeMs = newVal;\n"
"        document.getElementById(\"ms-value-text\").textContent = newVal;\n"
"        sendParamToCpp(\"delayTimeMs\", newVal);\n"
"    }\n"
"}\n"
"\n"
"// --------------------------------------------------------------------------\n"
"// Window Resize & Scaling Handler\n"
"// --------------------------------------------------------------------------\n"
"function handleWindowResize() {\n"
"    const w = window.innerWidth;\n"
"    const h = window.innerHeight;\n"
"    const scaleX = w / 1040;\n"
"    const scaleY = h / 1200;\n"
"    const scale = Math.min(scaleX, scaleY);\n"
"    const container = document.getElementById(\"app-container\");\n"
"    container.style.transform = `translate(-50%, -50%) scale(${scale})`;\n"
"}\n"
"\n"
"// --------------------------------------------------------------------------\n"
"// Global Event Listeners Registration\n"
"// --------------------------------------------------------------------------\n"
"\n"
"// Click events for basic controls\n"
"document.getElementById(\"power-btn\").onclick = () => {\n"
"    state.isEnabled = !state.isEnabled;\n"
"    updateUIFromState();\n"
"    sendParamToCpp(\"enabled\", state.isEnabled ? 1.0 : 0.0);\n"
"};\n"
"\n"
"\n"
"\n"
"document.querySelectorAll(\".matrix-btn\").forEach(btn => {\n"
"    btn.onclick = () => {\n"
"        if (!state.isEnabled) return;\n"
"        const div = btn.getAttribute(\"data-div\");\n"
"        state.syncDivision = div;\n"
"        \n"
"        // Update styling\n"
"        document.getElementById(\"manual-btn\").classList.remove(\"active\");\n"
"        document.getElementById(\"ms-value-box\").classList.remove(\"active\");\n"
"        document.querySelectorAll(\".matrix-btn\").forEach(b => b.classList.toggle(\"active\", b === btn));\n"
"        \n"
"        const index = SYNC_DIVISIONS.indexOf(div) + 1; // 1 to 18\n"
"        sendParamToCpp(\"syncDivision\", index);\n"
"    };\n"
"});\n"
"\n"
"document.getElementById(\"manual-btn\").onclick = () => {\n"
"    if (!state.isEnabled) return;\n"
"    state.syncDivision = 'ms';\n"
"    \n"
"    // Update styling\n"
"    document.getElementById(\"manual-btn\").classList.add(\"active\");\n"
"    document.getElementById(\"ms-value-box\").classList.add(\"active\");\n"
"    document.querySelectorAll(\".matrix-btn\").forEach(b => b.classList.remove(\"active\"));\n"
"    \n"
"    sendParamToCpp(\"syncDivision\", 0);\n"
"};\n"
"\n"
"document.getElementById(\"kill-btn\").onclick = () => {\n"
"    state.killOnStop = !state.killOnStop;\n"
"    document.getElementById(\"kill-btn\").classList.toggle(\"active\", state.killOnStop);\n"
"    sendParamToCpp(\"killOnStop\", state.killOnStop ? 1.0 : 0.0);\n"
"};\n"
"\n"
"document.getElementById(\"kill-on-switch-btn\").onclick = () => {\n"
"    state.killOnSwitch = !state.killOnSwitch;\n"
"    document.getElementById(\"kill-on-switch-btn\").classList.toggle(\"active\", state.killOnSwitch);\n"
"    sendParamToCpp(\"killOnSwitch\", state.killOnSwitch ? 1.0 : 0.0);\n"
"};\n"
"\n"
"document.querySelectorAll(\".snapshot-btn\").forEach(btn => {\n"
"    btn.onclick = () => {\n"
"        if (!state.isEnabled) return;\n"
"        const index = parseInt(btn.getAttribute(\"data-index\"));\n"
"        state.activeSnapshot = index;\n"
"        state.editSnapshot = index;\n"
"        updateUIFromState();\n"
"        sendParamToCpp(\"activeSnapshot\", index + 1);\n"
"    };\n"
"});\n"
"\n"
"document.querySelectorAll(\".snapshot-edit-btn\").forEach(btn => {\n"
"    btn.onclick = () => {\n"
"        if (!state.isEnabled) return;\n"
"        const index = parseInt(btn.getAttribute(\"data-index\"));\n"
"        state.editSnapshot = index;\n"
"        updateUIFromState();\n"
"        sendParamToCpp(\"editSnapshot\", index + 1);\n"
"    };\n"
"});\n"
"\n"
"document.getElementById(\"copy-snap-btn\").onclick = () => {\n"
"    if (!state.isEnabled) return;\n"
"    sendParamToCpp(\"copyActiveSnapshot\", 0);\n"
"};\n"
"\n"
"document.getElementById(\"paste-snap-btn\").onclick = () => {\n"
"    if (!state.isEnabled) return;\n"
"    sendParamToCpp(\"pasteActiveSnapshot\", 0);\n"
"};\n"
"\n"
"// Drag MS mouse registration\n"
"document.getElementById(\"ms-value-box\").onmousedown = (e) => {\n"
"    if (state.syncDivision !== 'ms') return;\n"
"    isDraggingMs = true;\n"
"    msStartY = e.clientY;\n"
"    msStartValue = state.delayTimeMs;\n"
"    document.body.style.cursor = 'ns-resize';\n"
"};\n"
"\n"
"// Drag Step Count mouse registration\n"
"document.getElementById(\"step-count-track\").onmousedown = (e) => {\n"
"    if (!state.isEnabled) return;\n"
"    isDraggingStepCount = true;\n"
"    updateStepCountFromMouse(e.clientX);\n"
"};\n"
"\n"
"// Global mouse tracking\n"
"window.addEventListener(\"mousemove\", (e) => {\n"
"    if (activeDraggingLane) {\n"
"        updateStepFromMouse(e, activeDraggingLane.element, activeDraggingLane.property, activeDraggingLane.min, activeDraggingLane.max, activeDraggingLane.isBipolar);\n"
"    } else if (isDraggingStepCount) {\n"
"        updateStepCountFromMouse(e.clientX);\n"
"    } else if (isDraggingMs) {\n"
"        updateMsFromMouse(e.clientY);\n"
"    }\n"
"});\n"
"\n"
"window.addEventListener(\"mouseup\", () => {\n"
"    activeDraggingLane = null;\n"
"    isDraggingStepCount = false;\n"
"    if (isDraggingMs) {\n"
"        isDraggingMs = false;\n"
"        document.body.style.cursor = 'default';\n"
"    }\n"
"});\n"
"\n"
"window.addEventListener(\"resize\", handleWindowResize);\n"
"\n"
"// --------------------------------------------------------------------------\n"
"// 3. APVTS C++ Callback Interface\n"
"// --------------------------------------------------------------------------\n"
"\n"
"const aetherUI = {\n"
"    initializeState: (jsonStateStr) => {\n"
"        try {\n"
"            const parsed = JSON.parse(jsonStateStr);\n"
"            state = parsed;\n"
"            updateUIFromState();\n"
"        } catch (e) {\n"
"            console.error(\"Error parsing initial state:\", e);\n"
"        }\n"
"    },\n"
"    updateParamFromCpp: (param, value) => {\n"
"        if (param === 'syncDivision') {\n"
"            const divStr = value === 0 ? 'ms' : SYNC_DIVISIONS[value - 1];\n"
"            if (state.syncDivision !== divStr) {\n"
"                state.syncDivision = divStr;\n"
"                updateUIFromState();\n"
"            }\n"
"            return;\n"
"        }\n"
"        if (param === 'activeSnapshot') {\n"
"            const index = value - 1;\n"
"            if (state.activeSnapshot !== index) {\n"
"                state.activeSnapshot = index;\n"
"                updateUIFromState();\n"
"            }\n"
"            return;\n"
"        }\n"
"        if (param === 'editSnapshot') {\n"
"            const index = value - 1;\n"
"            if (state.editSnapshot !== index) {\n"
"                state.editSnapshot = index;\n"
"                updateUIFromState();\n"
"            }\n"
"            return;\n"
"        }\n"
"        \n"
"        const keyMap = {\n"
"            'enabled': 'isEnabled',\n"
"            'delayTimeMs': 'delayTimeMs',\n"
"            'stepCount': 'stepCount',\n"
"            'killOnStop': 'killOnStop',\n"
"            'killOnSwitch': 'killOnSwitch'\n"
"        };\n"
"        const mappedKey = keyMap[param];\n"
"        if (mappedKey) {\n"
"            if (state[mappedKey] !== value) {\n"
"                state[mappedKey] = value;\n"
"                updateUIFromState();\n"
"            }\n"
"        }\n"
"    },\n"
"    updateStepsFromCpp: (jsonStepsStr) => {\n"
"        try {\n"
"            const parsedSteps = JSON.parse(jsonStepsStr);\n"
"            state.steps = parsedSteps;\n"
"            // Update individual step columns\n"
"            for (let i = 0; i < 15; i++) {\n"
"                updateStepUI(\"pitch\", i);\n"
"                updateStepUI(\"velocity\", i);\n"
"                updateStepUI(\"modwheel\", i);\n"
"                updateStepUI(\"probability\", i);\n"
"                updateStepUI(\"muted\", i);\n"
"            }\n"
"        } catch (e) {\n"
"            console.error(\"Error parsing steps:\", e);\n"
"        }\n"
"    }\n"
"};\n"
"\n"
"// Register bridge functions on mount\n"
"window.aetherUI = aetherUI;\n"
"\n"
"// Show build version in the bottom-right corner\n"
"(function() {\n"
"    const el = document.getElementById('build-version-label');\n"
"    if (el) el.textContent = BUILD_VERSION;\n"
"})();\n"
"\n"
"// Initialize app layout\n"
"buildLanes();\n"
"handleWindowResize();\n"
"// Request a full state sync from C++. This is queued via checkJuceBridge and fires\n"
"// only after window.__JUCE__ is available. C++ resets its caches; the timer then\n"
"// pushes all loaded parameter values to JS on its next tick (no reentrancy issues).\n"
"sendParamToCpp(\"queryall\", 0);\n";

const char* app_js = (const char*) temp_binary_data_1;

//================== styles.css ==================
static const unsigned char temp_binary_data_2[] =
"/* AETHER - Pure CSS Aesthetic Design System */\n"
"\n"
":root {\n"
"    --crt-green: #00ff41;\n"
"    --crt-green-dim: rgba(0, 255, 65, 0.2);\n"
"    --crt-green-hologram: rgba(0, 255, 65, 0.05);\n"
"    --crt-green-active: rgba(0, 255, 65, 0.4);\n"
"    --bg-darkest: #050505;\n"
"    --bg-main: #121212;\n"
"    --border-dim: #333333;\n"
"}\n"
"\n"
"* {\n"
"    box-sizing: border-box;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    user-select: none;\n"
"    -webkit-user-drag: none;\n"
"}\n"
"\n"
"body {\n"
"    background-color: var(--bg-darkest);\n"
"    color: var(--crt-green);\n"
"    font-family: 'IBM Plex Mono', monospace;\n"
"    overflow: hidden;\n"
"    height: 100vh;\n"
"    width: 100vw;\n"
"    display: flex;\n"
"    justify-content: center;\n"
"    align-items: center;\n"
"}\n"
"\n"
"/* CRT Scanline and Tint Overlay */\n"
".crt-overlay {\n"
"    position: fixed;\n"
"    top: 0;\n"
"    left: 0;\n"
"    width: 100vw;\n"
"    height: 100vh;\n"
"    background: linear-gradient(\n"
"        rgba(18, 16, 16, 0) 50%, \n"
"        rgba(0, 0, 0, 0.15) 50%\n"
"      ), linear-gradient(\n"
"        90deg, \n"
"        rgba(255, 0, 0, 0.03), \n"
"        rgba(0, 255, 0, 0.01), \n"
"        rgba(0, 0, 255, 0.03)\n"
"      );\n"
"    background-size: 100% 3px, 3px 100%;\n"
"    pointer-events: none;\n"
"    z-index: 999;\n"
"}\n"
"\n"
"/* Glow effects */\n"
".crt-glow {\n"
"    text-shadow: 0 0 8px var(--crt-green);\n"
"}\n"
"\n"
".crt-border {\n"
"    border: 1px solid var(--crt-green);\n"
"    box-shadow: inset 0 0 15px rgba(0, 255, 65, 0.15), 0 0 8px rgba(0, 255, 65, 0.15);\n"
"}\n"
"\n"
"/* Layout container */\n"
"#app-container {\n"
"    width: 1040px;\n"
"    height: 1200px;\n"
"    position: absolute;\n"
"    top: 50%;\n"
"    left: 50%;\n"
"    transform: translate(-50%, -50%) scale(1);\n"
"    transform-origin: center center;\n"
"    background-color: var(--bg-main);\n"
"    border: 1px solid var(--crt-green);\n"
"    box-shadow: inset 0 0 20px rgba(0, 255, 65, 0.1), 0 0 10px rgba(0, 255, 65, 0.15);\n"
"    padding: 30px;\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    justify-content: space-between;\n"
"    transition: opacity 0.5s ease, filter 0.5s ease;\n"
"}\n"
"\n"
"#app-container.disabled {\n"
"    opacity: 0.4;\n"
"    filter: grayscale(0.5);\n"
"    pointer-events: none;\n"
"}\n"
"\n"
"/* Utilities */\n"
".text-center { text-align: center; }\n"
".border-bottom { border-bottom: 1px solid rgba(0, 255, 65, 0.2); }\n"
".border-left { border-left: 1px solid rgba(0, 255, 65, 0.2); }\n"
".flex-1 { flex: 1; }\n"
".flex-2 { flex: 2; }\n"
".flex-3 { flex: 3; }\n"
"\n"
"/* Labels */\n"
".label-tiny {\n"
"    font-size: 9px;\n"
"    font-weight: 700;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.15em;\n"
"    opacity: 0.6;\n"
"    margin-bottom: 5px;\n"
"    display: block;\n"
"}\n"
"\n"
"/* Toggle Buttons */\n"
".toggle-btn {\n"
"    background: transparent;\n"
"    border: 1px solid rgba(0, 255, 65, 0.4);\n"
"    color: var(--crt-green);\n"
"    cursor: pointer;\n"
"    transition: all 0.2s ease;\n"
"    display: inline-flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"}\n"
"\n"
".toggle-btn:hover {\n"
"    background: rgba(0, 255, 65, 0.1);\n"
"}\n"
"\n"
".circular-btn {\n"
"    width: 48px;\n"
"    height: 48px;\n"
"    border-radius: 50%;\n"
"}\n"
"\n"
".square-btn {\n"
"    width: 32px;\n"
"    height: 32px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
".toggle-btn.active {\n"
"    background-color: var(--crt-green);\n"
"    color: black;\n"
"    border-color: var(--crt-green);\n"
"    box-shadow: 0 0 15px var(--crt-green);\n"
"}\n"
"\n"
"/* Header section styling */\n"
".main-header {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: stretch;\n"
"    padding-bottom: 24px;\n"
"    height: 160px;\n"
"}\n"
"\n"
".header-left {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 30px;\n"
"    flex: 1;\n"
"}\n"
"\n"
".control-group {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    justify-content: center;\n"
"    gap: 4px;\n"
"}\n"
"\n"
".branding {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    justify-content: center;\n"
"}\n"
"\n"
".logo {\n"
"    font-size: 64px;\n"
"    font-weight: 900;\n"
"    letter-spacing: -0.05em;\n"
"    line-height: 0.85;\n"
"}\n"
"\n"
".taglines {\n"
"    margin-top: 8px;\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"}\n"
"\n"
".tagline {\n"
"    font-size: 13px;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.15em;\n"
"    opacity: 0.6;\n"
"}\n"
"\n"
".subtagline {\n"
"    font-size: 12px;\n"
"    opacity: 0.6;\n"
"    margin-top: 2px;\n"
"}\n"
"\n"
"/* Delay Matrix styling */\n"
".delay-matrix-container {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    gap: 4px;\n"
"    min-width: 380px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
".section-label {\n"
"    opacity: 0.6;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
".matrix-grid {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(6, 1fr);\n"
"    gap: 0;\n"
"}\n"
"\n"
".matrix-btn {\n"
"    background: #121212;\n"
"    border: 1px solid rgba(0, 255, 65, 0.4);\n"
"    color: var(--crt-green);\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    height: 36px;\n"
"    cursor: pointer;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"    margin-left: -1px;\n"
"    margin-top: -1px;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
".matrix-btn:hover {\n"
"    background: rgba(0, 255, 65, 0.1);\n"
"    z-index: 10;\n"
"}\n"
"\n"
".matrix-btn.active {\n"
"    background: var(--crt-green);\n"
"    color: black;\n"
"    box-shadow: 0 0 15px rgba(0, 255, 65, 0.6);\n"
"    border-color: var(--crt-green);\n"
"    z-index: 10;\n"
"}\n"
"\n"
"/* Delay time footer elements */\n"
".delay-footer {\n"
"    display: flex;\n"
"    align-items: stretch;\n"
"    height: 36px;\n"
"    margin-top: -1px;\n"
"}\n"
"\n"
".delay-footer-btn {\n"
"    background: #121212;\n"
"    border: 1px solid rgba(0, 255, 65, 0.4);\n"
"    color: var(--crt-green);\n"
"    font-size: 9px;\n"
"    font-weight: 700;\n"
"    cursor: pointer;\n"
"    margin-left: -1px;\n"
"    transition: all 0.2s ease;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"}\n"
"\n"
".delay-footer-btn:hover {\n"
"    background: rgba(0, 255, 65, 0.1);\n"
"    z-index: 10;\n"
"}\n"
"\n"
".delay-footer-btn.active {\n"
"    background: var(--crt-green);\n"
"    color: black;\n"
"    border-color: var(--crt-green);\n"
"    z-index: 10;\n"
"}\n"
"\n"
".ms-drag-box {\n"
"    background: #121212;\n"
"    border: 1px solid rgba(0, 255, 65, 0.4);\n"
"    color: var(--crt-green);\n"
"    margin-left: -1px;\n"
"    cursor: ns-resize;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
".ms-drag-box:hover {\n"
"    background: rgba(0, 255, 65, 0.1);\n"
"}\n"
"\n"
".ms-drag-box.active {\n"
"    background: var(--crt-green);\n"
"    color: black;\n"
"    border-color: var(--crt-green);\n"
"    box-shadow: 0 0 15px rgba(0, 255, 65, 0.6);\n"
"}\n"
"\n"
".ms-drag-box span {\n"
"    font-size: 14px;\n"
"    font-weight: 900;\n"
"}\n"
"\n"
"/* Lanes workspace styling */\n"
".lanes-workspace {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    gap: 16px;\n"
"    flex: 1;\n"
"    margin-top: 20px;\n"
"}\n"
"\n"
".lane-wrapper {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    gap: 6px;\n"
"}\n"
"\n"
".lane-header {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"    padding: 0 4px;\n"
"}\n"
"\n"
".lane-title-group {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 16px;\n"
"}\n"
"\n"
".lane-title {\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.1em;\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
".lane-actions {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 8px;\n"
"}\n"
"\n"
".action-btn {\n"
"    background: transparent;\n"
"    border: 1px solid transparent;\n"
"    color: rgba(0, 255, 65, 0.6);\n"
"    cursor: pointer;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
".action-btn:hover {\n"
"    color: var(--crt-green);\n"
"    border-color: rgba(0, 255, 65, 0.3);\n"
"}\n"
"\n"
".action-btn:active {\n"
"    background: var(--crt-green);\n"
"    color: black;\n"
"}\n"
"\n"
"/* Grid of steps inside a lane */\n"
".steps-grid {\n"
"    display: flex;\n"
"    gap: 4px;\n"
"    padding: 0 4px;\n"
"    position: relative;\n"
"}\n"
"\n"
".bipolar-center-line {\n"
"    position: absolute;\n"
"    left: 4px;\n"
"    right: 4px;\n"
"    height: 1px;\n"
"    background: rgba(0, 255, 65, 0.15);\n"
"    pointer-events: none;\n"
"    z-index: 10;\n"
"}\n"
"\n"
"/* Single Step Column */\n"
".step-column {\n"
"    flex: 1;\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    cursor: crosshair;\n"
"    transition: opacity 0.3s ease;\n"
"}\n"
"\n"
".step-column.inactive {\n"
"    opacity: 0.2;\n"
"}\n"
"\n"
".step-bar-container {\n"
"    flex: 1;\n"
"    border: 1px solid rgba(0, 255, 65, 0.3);\n"
"    background-color: #121212;\n"
"    position: relative;\n"
"    overflow: hidden;\n"
"}\n"
"\n"
"/* Step heights & indicators */\n"
".step-bar-fill {\n"
"    position: absolute;\n"
"    bottom: 0;\n"
"    left: 0;\n"
"    right: 0;\n"
"    background-color: var(--crt-green);\n"
"    box-shadow: 0 0 8px rgba(0, 255, 65, 0.6);\n"
"    pointer-events: none;\n"
"}\n"
"\n"
".step-bar-bipolar {\n"
"    position: absolute;\n"
"    left: 0;\n"
"    right: 0;\n"
"    background-color: var(--crt-green);\n"
"    box-shadow: 0 0 8px rgba(0, 255, 65, 0.6);\n"
"    pointer-events: none;\n"
"}\n"
"\n"
".step-mute-box {\n"
"    width: 100%;\n"
"    height: 100%;\n"
"    transition: background-color 0.2s ease;\n"
"}\n"
"\n"
".step-mute-box.unmuted {\n"
"    background-color: var(--crt-green);\n"
"    box-shadow: 0 0 8px rgba(0, 255, 65, 0.6);\n"
"}\n"
"\n"
".step-mute-box.muted {\n"
"    background-color: rgba(0, 255, 65, 0.05);\n"
"}\n"
"\n"
".step-value-label {\n"
"    height: 28px;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"    font-size: 16.5px;\n"
"    font-weight: 900;\n"
"    margin-top: 2px;\n"
"    pointer-events: none;\n"
"}\n"
"\n"
"/* Step Count Slider */\n"
".step-count-container {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    gap: 4px;\n"
"    margin-top: 10px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
".step-count-track {\n"
"    height: 24px;\n"
"    background: #1a1a1a;\n"
"    border: 1px solid #333333;\n"
"    display: flex;\n"
"    gap: 2px;\n"
"    padding: 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
".step-count-segment {\n"
"    flex: 1;\n"
"    background-color: rgba(0, 255, 65, 0.05);\n"
"    transition: background-color 0.2s ease;\n"
"}\n"
"\n"
".step-count-segment.active {\n"
"    background-color: var(--crt-green);\n"
"    box-shadow: 0 0 5px rgba(0, 255, 65, 0.3);\n"
"}\n"
"\n"
"/* Snapshots Preset Section */\n"
".snapshot-container {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    gap: 8px;\n"
"    margin-top: 16px;\n"
"    border-top: 1px solid rgba(0, 255, 65, 0.2);\n"
"    padding-top: 12px;\n"
"}\n"
"\n"
".snapshot-header {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 16px;\n"
"    margin-bottom: 4px;\n"
"}\n"
"\n"
".snapshot-actions {\n"
"    display: flex;\n"
"    gap: 8px;\n"
"}\n"
"\n"
".snapshot-actions .action-btn {\n"
"    font-family: 'IBM Plex Mono', monospace;\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    width: 22px;\n"
"    height: 22px;\n"
"    border: 1px solid rgba(0, 255, 65, 0.4);\n"
"    background: #121212;\n"
"    color: var(--crt-green);\n"
"    cursor: pointer;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"    transition: all 0.2s ease;\n"
"    padding: 0;\n"
"}\n"
"\n"
".snapshot-actions .action-btn:hover {\n"
"    background: rgba(0, 255, 65, 0.2);\n"
"    box-shadow: 0 0 5px rgba(0, 255, 65, 0.4);\n"
"}\n"
"\n"
".snapshot-actions .wide-action-btn {\n"
"    width: auto;\n"
"    padding: 0 6px;\n"
"    font-size: 10px;\n"
"    white-space: nowrap;\n"
"}\n"
"\n"
".snapshot-actions .wide-action-btn.active {\n"
"    background: var(--crt-green);\n"
"    color: black;\n"
"    box-shadow: 0 0 8px rgba(0, 255, 65, 0.6);\n"
"}\n"
"\n"
".snapshot-radio-group {\n"
"    display: flex;\n"
"    gap: 8px;\n"
"    margin-bottom: 6px;\n"
"}\n"
"\n"
".snapshot-edit-group {\n"
"    display: flex;\n"
"    gap: 8px;\n"
"}\n"
"\n"
".snapshot-btn {\n"
"    flex: 1;\n"
"    background: #121212;\n"
"    border: 1px solid rgba(0, 255, 65, 0.4);\n"
"    color: var(--crt-green);\n"
"    font-family: 'IBM Plex Mono', monospace;\n"
"    font-size: 14px;\n"
"    font-weight: 700;\n"
"    height: 36px;\n"
"    cursor: pointer;\n"
"    border-radius: 2px;\n"
"    transition: all 0.2s ease;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"}\n"
"\n"
".snapshot-edit-btn {\n"
"    flex: 1;\n"
"    height: 14px;\n"
"    background: transparent;\n"
"    border: 1px solid rgba(0, 255, 65, 0.4);\n"
"    border-radius: 50%;\n"
"    cursor: pointer;\n"
"    padding: 0;\n"
"    max-width: 14px;\n"
"    margin: 0 auto;\n"
"    transition: all 0.2s;\n"
"}\n"
"\n"
".snapshot-edit-btn:hover {\n"
"    border-color: var(--crt-green);\n"
"}\n"
"\n"
".snapshot-edit-btn.active {\n"
"    background: var(--crt-green);\n"
"    border-color: var(--crt-green);\n"
"    box-shadow: 0 0 5px rgba(0, 255, 65, 0.5);\n"
"}\n"
"\n"
".snapshot-btn:hover {\n"
"    background: rgba(0, 255, 65, 0.1);\n"
"}\n"
"\n"
".snapshot-btn.active {\n"
"    background: var(--crt-green);\n"
"    color: black;\n"
"    border-color: var(--crt-green);\n"
"    box-shadow: 0 0 15px rgba(0, 255, 65, 0.6);\n"
"}\n"
"\n"
"/* Fix: Allow power button to be interactive when app is disabled */\n"
"#power-btn {\n"
"    pointer-events: auto !important;\n"
"}\n";

const char* styles_css = (const char*) temp_binary_data_2;


const char* getNamedResource (const char* resourceNameUTF8, int& numBytes);
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)
{
    unsigned int hash = 0;

    if (resourceNameUTF8 != nullptr)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0x2c834af8:  numBytes = 7499; return index_html;
        case 0xabe4b827:  numBytes = 23514; return app_js;
        case 0x096a0926:  numBytes = 11851; return styles_css;
        default: break;
    }

    numBytes = 0;
    return nullptr;
}

const char* namedResourceList[] =
{
    "index_html",
    "app_js",
    "styles_css"
};

const char* originalFilenames[] =
{
    "index.html",
    "app.js",
    "styles.css"
};

const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8);
const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)
{
    for (unsigned int i = 0; i < (sizeof (namedResourceList) / sizeof (namedResourceList[0])); ++i)
        if (strcmp (namedResourceList[i], resourceNameUTF8) == 0)
            return originalFilenames[i];

    return nullptr;
}

}
